### ISSUE TITLE
NetConfClient SendReceiveRpc with AutomaticMessageIdHandling can cause NullReferenceException

### ISSUE THREAD

**Issue by tloader11** [zeevl/Renci.SshNet#3]
Renci.SshNet/Netconf/NetConfSession.cs -> _messageId is undefined when calling SendReceiveRpc.

The following code:
```
            var netConfClient = new NetConfClient("hostname.here", 830, "usernamehere", "passwordhere");
            
            netConfClient.Connect();

            if (netConfClient.IsConnected)
            {
                XmlDocument rpc = new XmlDocument();
                rpc.LoadXml("<rpc><get-interface-information></get-interface-information></rpc>");

                var rpcResponse = netConfClient.SendReceiveRpc(rpc);

                Console.Write(rpcResponse.OuterXml);
            }
```

This causes the following issue:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Renci.SshNet.NetConf.NetConfSession.SendReceiveRpc(XmlDocument rpc, Boolean automaticMessageIdHandling)
   at Renci.SshNet.NetConfClient.SendReceiveRpc(XmlDocument rpc)
```

Currently using 
```
AutomaticMessageIdHandling = false
```
to bypass this issue.

Proposed fix is init'ing the _messageId in the constructor.

**Comment by MagnusArias** [comment]
I found the error in source code:
https://github.com/zeevl/Renci.SshNet/blob/67f88dcaf8117b2e1bf11012c5a23e937c551d1d/Renci.SshNet/Netconf/NetConfSession.cs#L62

Line 62, inappropriate usage of "_messageID" variable. This variable never had value assigned. Alternatively, you can set "automaticMessageIdHandling" to "false" and it works then
